name: Deploy to Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli

      - name: Run npm install
        run: npm i

      - name: Set deployment folder
        run: echo "DEPLOY_FOLDER=site" >> $GITHUB_ENV

      - name: Build Angular
        run: |
          ng build ncrt-books
          ng build --configuration production --output-path ${{ env.DEPLOY_FOLDER }} --base-href /ncrt-books/

      - name: Move files to deployment folder
        run: |
          mv ${{ env.DEPLOY_FOLDER }}/browser/* ${{ env.DEPLOY_FOLDER }}/ 
          rm -rf ${{ env.DEPLOY_FOLDER }}/browser

      - name: Copy SchoolBooks folder
        run: cp -r SchoolBooks ${{ env.DEPLOY_FOLDER }}/

      - uses: EndBug/add-and-commit@v7
        with:
          add: "${{ env.DEPLOY_FOLDER }}"
          default_author: github_actions
          message: "Lesson Question and Answer"
